function [] = save2tikz(name, varargin)
    cleanfigure();

    matlab2tikz([name, '.tikz'], 'height', '\figureheight', 'width', '\figurewidth', 'showInfo', false, ...
        'extraaxisoptions', ['xlabel style={font=\small},', ...
        'ylabel style={font=\small},', ...
        'ticklabel style={font=\footnotesize},', ...
        'legend style={font=\footnotesize}'] ...
        );
end
